version: '3'

services:
  website:
    build: .
    volumes:
      - .:/opt/services/djangoapp/src
    networks:
      - nginx_network

  nginx:
    image: nginx:1.15
    ports:
      - 8000:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - website
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge