version: '3'

services:
  website:
    build: .
    image: website
    volumes:
      - .:/opt/services/website/src
      - static_volume:/opt/services/website/static
      - media_volume:/opt/services/website/media
    networks:
      - nginx_network
      - website_db_network
      - collector_network
    depends_on:
      - website_db
    command: ["gunicorn", "--bind", ":8000", "website.wsgi:application"]

  nginx:
    image: nginx:1.15
    ports:
      - "8000:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/opt/services/website/static
      - media_volume:/opt/services/website/media
    depends_on:
      - website
    networks:
      - nginx_network

  website_db:
    build:
      context: ./postgresql
      dockerfile: Dockerfile
    image: website_db
    env_file:
      - ./postgresql/env
    networks:
      - website_db_network
    volumes:
      - website_db_volume:/var/lib/postgresql/data

  collector:
    build:
      context: ../collector
      dockerfile: Dockerfile
    image: collector
    networks:
      - website_db_network
      - collector_network
    depends_on:
      - website_db

networks:
  nginx_network:
    driver: bridge
  website_db_network:
    driver: bridge
  collector_network:
    driver: bridge

volumes:
  website_db_volume:
  static_volume:
  media_volume: