# Generated by Django 2.1.4 on 2018-12-19 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ali', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='alisearch',
            table='ali_search',
        ),
    ]
