# Generated by Django 2.1.4 on 2018-12-19 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ali', '0002_auto_20181219_1051'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AliSearch',
            new_name='Search',
        ),
        migrations.AlterModelTable(
            name='search',
            table=None,
        ),
    ]
