# Generated by Django 2.1.4 on 2019-01-07 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ali', '0004_tracker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Throttler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.TextField(verbose_name='ip address')),
                ('session_id', models.TextField(verbose_name='session id')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
            ],
        ),
    ]
