CREATE ROLE ali WITH LOGIN CREATEDB PASSWORD 'ali';
CREATE DATABASE ali OWNER ali;
GRANT ALL PRIVILEGES ON DATABASE ali TO ali;
CREATE ROLE website WITH LOGIN CREATEDB PASSWORD 'website';
CREATE DATABASE website OWNER website;
GRANT ALL PRIVILEGES ON DATABASE website TO website;